before_script:
  - mkdir -p ~/.ssh
  - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

deploy:
  type: deploy
  environment:
    name: prod
  script:
    - ssh -i ~/.ssh/id_rsa ubuntu@thesis.tkhco.com.vn /home/ubuntu/thesis/hung/deploy.sh
  only:
    - master