version: "3.3"

services:     
  backend:
    container_name: ocr_server
    build: main
    command: bash -c "python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./main:/code
    ports:
      - "8000:8000"
