IMAGE_CROPER:
  MORPH: 9
  CANNY: 75
  HOUGH: 25
  BLUR: 3
CALIBRATION:
  ENABLE: False
  RATE: 0.01
HORIZONTAL_DETECT:
  RATE: 0.52
TEXT_DETECTION:
  IM_SCALE: 1020
  VETICAL_PADDING: 0.1
TEXT_COMBINE:
  MAX_WIDTH_MULTIPLY: 8
  NUM_SPACE_MARK_AS_TAB: 1
  SPACE_OVER_CHARATER: 2 
TEXT_CLASSIFICATION:
  JSON_PATH: text_classification/model/model_sequence_grouped.json
  M5_PATH: text_classification/model/model_sequence_grouped.h5
  TOKENIZER_PATH: text_classification/model/tokenizer_sequence_grouped.pickle
  MAX_WORD_COUNT: 450
  MIN_CONF_TO_SAVE: 0.6