IMAGE_CROPER:
  MORPH: 9
  CANNY: 84
  HOUGH: 25
  BLUR: 3
CALIBRATION:
  ENABLE: False
  RATE: 0.01
HORIZONTAL_DETECT:
  RATE: 0.52
TEXT_COMBINE:
  MAX_WIDTH_MULTIPLY: 8
  NUM_SPACE_MARK_AS_TAB: 1
  SPACE_OVER_CHARATER: 2 